### PR TITLE
83 Fix type specs

### LINKED ISSUE #83: Fix type specs
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!

### Description

Fix type specs

### Current behavior

Some typespecs are wrong.

### Expected behavior

- [ ] Add error in typespec from `persist_changes` in accounts
- [ ] Change spec for ids from `String.t()` to `UUID.t()`
- [ ] Change spec of `Account.t()` to `%MODULE{}` in Accounts

### PR DESCRIPTION
**Pull request by miguelnietoa**
## Description

Fixes #83 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by einerzg — APPROVED** [review]

File: apps/mintacoin/lib/mintacoin/accounts/schema.ex [hunk 1]
```diff
@@ -44,7 +44,7 @@ defmodule Mintacoin.Account do
     timestamps()
   end
 
-  @spec changeset(account :: Account.t(), changes :: map()) :: Changeset.t()
+  @spec changeset(account :: t(), changes :: map()) :: Changeset.t()
```
Comment (einerzg) [inline apps/mintacoin/lib/mintacoin/accounts/schema.ex:47]: why do you use `t()` in this line and `%_MODULE_{}` in line 59? it's better to use `t()` for both cases? what do you think?

**Review by einerzg — CHANGES_REQUESTED** [review]

File: apps/mintacoin/lib/mintacoin/accounts/schema.ex (hunk 1 above)
Comment (miguelnietoa) [reply apps/mintacoin/lib/mintacoin/accounts/schema.ex:47]: `t()` means an Account struct with the fields defined, so when you call `changeset` it is because you want to update an existing Account.

In line 59, we cannot use `t()` because the `create_changeset` will be called with an empty Account struct (`%Account{}`). So at that moment, we don't have an Account struct with defined fields.

Comment (einerzg) [reply apps/mintacoin/lib/mintacoin/accounts/schema.ex:47]: you right!!!

**Review by einerzg — APPROVED** [review]

File: apps/mintacoin/lib/mintacoin/accounts/schema.ex (hunk 1 above)
Comment (miguelnietoa) [reply apps/mintacoin/lib/mintacoin/accounts/schema.ex:47]: Thanks @einerzg 👍🏻
